import type { RiskLevel } from "../../risk/types";

const GITHUB_API_BASE = "https://api.github.com";
const GITHUB_API_VERSION = "2022-11-28";

export interface CreateCheckRunInput {
  installationId: number;
  owner: string;
  repo: string;
  headSha: string;
  riskScore: number;
  riskLevel: RiskLevel;
  summary: string;
}

export interface CreateCheckRunResult {
  id: number;
  htmlUrl: string;
}

/**
 * Maps risk levels to standard GitHub Check conclusions.
 */
export function getCheckConclusionForLevel(
  level: RiskLevel
): "success" | "neutral" | "failure" {
  switch (level) {
    case "CRITICAL":
      return "failure";
    case "HIGH":
      return "neutral";
    case "MEDIUM":
    case "LOW":
    default:
      return "success";
  }
}

/**
 * Creates a completed Check Run on GitHub representing the risk assessment.
 */
export async function createCheckRun(
  input: CreateCheckRunInput
): Promise<CreateCheckRunResult> {
  const { installationId, owner, repo, headSha, riskScore, riskLevel, summary } =
    input;

  const { getInstallationAccessToken } = await import("./index");
  const token = await getInstallationAccessToken(installationId);
  const conclusion = getCheckConclusionForLevel(riskLevel);

  const response = await fetch(
    `${GITHUB_API_BASE}/repos/${owner}/${repo}/check-runs`,
    {
      method: "POST",
      headers: {
        Authorization: `token ${token}`,
        Accept: "application/vnd.github+json",
        "X-GitHub-Api-Version": GITHUB_API_VERSION,
        "User-Agent": "ContextHub-AI",
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        name: "ContextHub Risk Assessment",
        head_sha: headSha,
        status: "completed",
        conclusion,
        output: {
          title: `Risk Score: ${riskScore}/10 — ${riskLevel}`,
          summary: `Assessment generated by ContextHub AI.`,
          text: summary,
        },
      }),
    }
  );

  if (!response.ok) {
    const errorText = await response.text();
    throw new Error(
      `Failed to create check run: ${response.status} ${response.statusText} — ${errorText}`
    );
  }

  const data = (await response.json()) as { id: number; html_url: string };

  return {
    id: data.id,
    htmlUrl: data.html_url,
  };
}
